enabled = True

interval = 3600
measure_collector_time = False
byte_unit = byte,
ttl_multiplier = 2

# Comma-separated hosts. Use host:port for custom ports.
# hosts = example.com, google.com:443, piathome.freeboxos.fr
hosts = piathome.freeboxos.fr
